account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("", views.account, name="account"),
    path("kyc-registration/", views.kyc_registration, name="kyc-registration"),
]

bank_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include("user_auths.urls")),
    path("account/", include("account.urls")),
    path("", include("main_app.urls")),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_auths/urls.py
from django.urls import path
from user_auths import views

app_name = "user_auths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("logout/", views.logout_view, name="logout"),
]

templates/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bank App</title>
    <link rel="shortcut icon" href="{% static 'assets/images/fav.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>

<body>
    <!-- header-section start -->
    <header class="header-section">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex header-area">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="index.html">
                            <img src="{% static 'assets/images/logo.png' %}" class="logo" alt="logo">
                        </a>
                        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbar-content">
                            <i class="fas fa-bars"></i>
                        </button>
                        <div class="collapse navbar-collapse justify-content-end" id="navbar-content">
                            <div class="right-area header-action d-flex align-items-center max-un">
                                {% if request.user.is_authenticated %}
                                    <a href="{% url "user_auths:logout" %}" class="cmn-btn">Sign Out</a>
                                {% else %}
                                    <a href="{% url "user_auths:sign-in" %}" class="login">Login</a>
                                    <a href="{% url "user_auths:sign-up" %}" class="cmn-btn">Sign Up
                                        <i class="icon-d-right-arrow-2"></i>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Alert Start-->
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                <strong>{{message}}</strong>
            </div>
            {% endfor %}
        {% endif %}
        <script>
                    setTimeout (() => {
                        $(".alert").alert("close");
                    }, 4000)
        </script>
        
        <!-- Alert end -->
    </header>

    <!-- header-section end -->

    {% block content %}
    
    {% endblock content %}

     <!--==================================================================-->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/fontawesome.js' %}"></script>
    <script src="{% static 'assets/js/plugin/slick.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/counter.js' %}"></script>
    <script src="{% static 'assets/js/plugin/waypoint.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/plugin.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>