account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("", views.account, name="account"),
    path("kyc-registration/", views.kyc_registration, name="kyc-registration"),
]

bank_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include("user_auths.urls")),
    path("account/", include("account.urls")),
    path("", include("main_app.urls")),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from main_app import views, transfer, transaction, payment_request, card

app_name = "main_app"

urlpatterns = [
    path("", views.index, name="index"),
    
    #Transfers
    path("find-account/", transfer.find_user_by_account, name="find-account"),
    path("amount-transfer/<account_number>/", transfer.amount_transfer, name="amount-transfer"),
    path("amount-transfer-process/<account_number>/", transfer.amount_transfer_process, name="amount-transfer-process"),
    path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.transfer_confirmation, name="transfer-confirmation"),
    path("transfer-process/<account_number>/<transaction_id>/", transfer.transfer_process, name="transfer-process"),
    path("transfer-completed/<account_number>/<transaction_id>/", transfer.transfer_completed, name="transfer-completed"),
    
     # transactions
    path("transactions/", transaction.transaction_lists, name="transactions"),
    path("transaction-details/<transaction_id>/", transaction.transaction_details, name="transaction-details"),
    
    # Payment Request
    path("request-search-account/", payment_request.search_user_request, name="request-search-account"),
    path("amount-request/<account_number>/", payment_request.amount_request, name="amount-request"),
    path("amount-request-process/<account_number>/", payment_request.amount_request_process, name="amount-request-process"),
    path("amount-request-confirmation/<account_number>/<transaction_id>/", payment_request.amount_request_confirmation, name="amount-request-confirmation"),
    path("request-processing-permission/<account_number>/<transaction_id>/", payment_request.request_processing_permission, name="request-processing-permission"),
    path("request-completed/<account_number>/<transaction_id>/", payment_request.request_completed, name="request-completed"),
    
    # Request Settlement
    path("settlement-confirmation/<account_number>/<transaction_id>/", payment_request.settlement_confirmation, name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/", payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/", payment_request.settlement_completed, name="settlement-completed"),
    path("delete-request/<account_number>/<transaction_id>/", payment_request.delete_payment_request, name="delete-request"),
    
    # Card
    path("card/<card_id>/", card.card_detail, name="card-detail"),
    path("fund-card/<card_id>/", card.fund_card, name="fund-card"),
    path("withdraw_fund/<card_id>/", card.withdraw_fund, name="withdraw_fund"),
    path("delete_card/<card_id>/", card.delete_card, name="delete_card"),
]

templates/payment_request/amount-request-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Request</h4>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Your Request</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ account.user.email }}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    <a href="{% url 'main_app:request-search-account' %}">
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Request Details</h6>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>Request</span>
                                        <b>{{transaction.amount}} USD</b>
                                    </li>
                                    <li>
                                        <span>From</span>
                                        <b>{{account.user.kyc.full_name|title}}</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Description</span>
                                        <b>{{transaction.description}}</b>
                                    </li>
                                    <li>
                                        <span>Transfer was initiated on </span>
                                        <b>{{transaction.date}} </b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="footer-area mt-40">
                            <a href="{% url 'main_app:find-account' %}">Back</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Make Request</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

   <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content modalconfirm">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>Enter your pin number below.</p>
                                             <form action="{% url "main_app:request-processing-permission" account.account_number transaction.transaction_id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput col-xl-12">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="text">
                                                </div>

                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->

{% endblock content %}

templates/payment_request/amount-request.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Set request amount</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;" src="{{ account.user.kyc.image.url }} " alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ account.user.email }}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    <a href="{% url 'main_app:find-account' %}">
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{% url "main_app:amount-request-process" account.account_number %}" method="POST">
                        {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">Your request</span>
                            <div class="input-area">
                                <input 
                                    class="xxlr" 
                                    placeholder="Enter request amount" 
                                    type="number" 
                                    name="amount-request" 
                                    id="amount-request"
                                >
                                <select>
                                    <option value="1">USD</option>
                                </select>
                            </div>
                        </div>

                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">Request Description</span>
                            <div class="input-area">
                                <input 
                                    class="xxlr"  
                                    placeholder="Request" 
                                    type="text" 
                                    name="description"
                                >
                            </div>
                        </div>

                        
                        <div class="footer-area mt-40">
                            <a href="{% url 'main_app:request-search-account' %}">Previous Step</a>
                            <button type="submit" style="padding: 10px 30px; border-radius: 10px; background: rgb(98, 0, 255); color: #fff;" class="active">Next</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

{% endblock content %}

templates/payment_request/request-completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Request</h4>
                        <div class="icon-area">
                            <!-- <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon"> -->
                        </div>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                            </div>
                            <h3>Request Sent</h3>
                            <p>Rquest of <b>${{transaction.amount}}</b> was sent to <b>{{account.user.kyc.full_name}}</b></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
{% endblock content %}

templates/payment_request/request-search-account.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request Payment</h4>

                    </div>

                    <form class="flex-fill" method="POST">
                        {% csrf_token %}
                        <div class="form-group d-flex align-items-center">
                            <img src="{% static 'assets1/images/icon/search.png' %}" alt="icon">
                            <input type="text" name="account_number" placeholder="Enter Account Number or ID">
                            <button type="submit" style="border-radius: 40%;"><i class="fas fa-angle-right" ></i></button>
                        </div>
                    </form>
                    <div class="user-select">
                        {% if query %}
                        {% for account in accounts %}
    
                        <div class="single-user">
                            <div class="left d-flex align-items-center">
                                <div class="img-area">
                                    <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
                                </div>
                                <div class="text-area">
                                    <p>{{ account.user.kyc.full_name|title }}</p>
                                    <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                    <span class="mdr">{{ account.user.email }}</span>
                                </div>
                            </div>
                            <div class="right">
                                
                                <a  href="{% url 'main_app:amount-request' account.account_number  %}">
                                    Choose
                                </a>
                            </div>
                        </div>
                        {% empty %}
                            <div>
                                <h4 class="mt-5">Account does not exist.</h4>
                            </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    {% comment %} <div class="footer-area mt-40">
                        <a href="pay.html">Previous Step</a>
                        <a href="pay-step-2.html" class="active">Next</a>
                    </div> {% endcomment %}
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->


{% endblock content %}

templates/payment_request/settlement-completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Payment made</h4>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                            </div>
                            <h3>Money Sent</h3>
                            <p>Request payment of <b>${{transaction.amount}}</b> was sent to <b>{{account.user.kyc.full_name}}</b></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
{% endblock content %}

templates/payment_request/settlement-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request from {{ account.user.kyc.full_name|title }}</h4>
                    </div>
                    <div class="choose-recipient">
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ account.user.email }}</span>
                                    </div>
                                </div>
                                <div class="right">
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Request Details</h6>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>You Send</span>
                                        <b>{{transaction.amount}} USD</b>
                                    </li>
                                    <li>
                                        <span>Recipient gets</span>
                                        <b>{{transaction.amount}} USD</b>
                                    </li>
                                    <li>
                                        <span>E-mail of receiver</span>
                                        <b>{{account.user.email}}</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Description</span>
                                        <b>{{transaction.description}}</b>
                                    </li>
                                    <li>
                                        <span>Transfer was initiated on </span>
                                        <b>{{transaction.date}} </b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="footer-area mt-40">
                            <a href="{% url 'main_app:transactions' %}">Back</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Pay</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

   <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content modalconfirm">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>Enter your pin number below.</p>
                                             <form action="{% url 'main_app:settlement-processing' account.account_number transaction.transaction_id  %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput col-xl-12">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="text">
                                                </div>

                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->

{% endblock content %}